### ISSUE TITLE
"not ok 18 - push commits with copy and rename"

### ISSUE THREAD

**Issue by FauxFaux** [mnauw/git-remote-hg#11]
`test-push.t` fails for me on Debian sid. I don't really understand what it's doing, so I can't really work out why.

cf. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844939

```
Cloning into 'gitrepo'...
requesting all changes
adding changesets
adding manifests
adding file changes
added 1 changesets with 1 changes to 1 files
new changesets 6f6ffe13c16f
progress revision walk 'bookmarks/master' (0/0)
progress revision 0 'master' (0/1)
[master b3130fb] copy
 Author: A U Thor <author@example.com>
 2 files changed, 2 insertions(+), 1 deletion(-)
 create mode 100644 content-copy
[master fd1a6bf] moved
 Author: A U Thor <author@example.com>
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename content-copy => content-moved (100%)
searching for changes
no changes found
searching for changes
adding changesets
adding manifests
adding file changes
added 2 changesets with 3 changes to 3 files
To hg::/root/src/git-remote-hg/test/trash directory.main-push/hgrepo
   fffffff..fd1a6bf  master -> master
2 files updated, 0 files merged, 0 files removed, 0 files unresolved
not ok 18 - push commits with copy and rename
```

At the end, it looks like it's checking for three changesets, but there are only two?
```
# hg log -f content-moved
changeset:   2:beb6c5cbcf9d
tag:         tip
user:        ...
date:        Tue Nov 28 12:01:07 2017 +0000
summary:     moved

changeset:   1:5f44b7021c3b
user:        ...
date:        Tue Nov 28 12:01:07 2017 +0000
summary:     copy
```

hg-remote-helper HEAD (76be528), hg 4.4.1, git 2.15.0, python 2.7.14, locales-all 2.25-2, amd64 docker on 4.13 / btrfs; running as root.

Any guesses, or anything else I can provide to help?

**Comment by mnauw** [comment]
It looks like behaviour of `git log -M -C` has changed a bit across version in what it detects as copies.  Even worse, in git 2.15.0 `git log` might still report something as a copy (for some combination of command line options), whereas `git fast-export` does not report it as a copy (with same options).  However, checking the proper behaviour of all that is more a matter for git tests, whereas git-remote-hg tests are to check that it behaves properly (based on reported copy/rename).  So I will tweak the test scenario into something that all git versions properly report as copy/rename (at least in my setting with those versions, please do note if somehow not so in your setting).

**Comment by mnauw** [comment]
For the record, the aforementioned changed behaviour of `git fast-export` can be tracked down to git/git@8096e1d385660c159d9d47e69b2be63cf22e4f31.  Although the change make sense for the reasons specified there, the side-effect is a somewhat unfortunate loss of information for exporters/bridges (such as git-remote-hg).

**Comment by mnauw** [comment]
One more for the record ... it is actually possible to tweak `git-fast-export` in a way that would address what had to be fixed there while avoiding loss of information for exporters/bridges (by remaining close enough to the old behaviour).  Patches have been provided to the git mailing list; see e.g. https://public-inbox.org/git/1514112729-31647-1-git-send-email-mark.nauwelaerts@gmail.com/.  However, they seem to be falling on deaf ears.  So if anyone has better PR skills or is otherwise more persuasive in getting these patches to be considered in some way ...
