### ISSUE TITLE
A pip package

### ISSUE THREAD

**Issue by azmeuk** [mnauw/git-remote-hg#13]
Hi, congratulations for you project. So far it is the only version of git-remote-hg I have seen working with mercurial 4.5. Did you consider to release a pip package ? That would make the installation easier!

**Comment by mnauw** [comment]
Thanks!  Since this is so far "only" a fork, I have not really considered a release version, distribution, packaging and things like that.  Not minding about all that is also helped by the fact that it can be installed by only dropping a script into `PATH`.  However, if there is (increasing) demand, I could consider some additional polishing here or there (e.g. pip).

**Comment by azmeuk** [comment]
I just emailed @rfk the author of [this git-remote-hg](https://github.com/rfk/git-remote-hg) to ask him if he would consider giving access to the `git-remote-hg` pypi repository, since he has no intention to maintain his project.

**Comment by rfk** [comment]
Thanks for reaching out, I'd be happy to hand over the package name on PyPI.  My only request would be that we make it a semantic major version bump to help make it clearer that it's a different version of the package.

**Comment by mnauw** [comment]
It should not be a problem giving it version 1.4.0 (based on 0.4 here), or bump versions (synced) altogether (to e.g. 1.0).  In any case, something along those lines ...

**Comment by rfk** [comment]
Sounds good, let me know if/when you want to go ahead with this and your PyPI username, and I'll look into transferring ownership.

**Comment by mnauw** [comment]
Ok, thanks, so I setup a PyPI account and my PyPI username there is (also) mnauw.

**Comment by rfk** [comment]
@mnauw I've made you an owner of the project on PyPI, let me know if anything doesn't seem to be working as it should.

**Comment by mnauw** [comment]
@rfk ok thanks, I'll try to come up with a new release and will let you know if I run into any bumps.
