### ISSUE TITLE
Any release comming soon?

### ISSUE THREAD

**Issue by solbu** [mnauw/git-remote-hg#17]
Hi.
I am a packager for Mageia, and found this tool today, and plan to package it for Mageia.
Your current releases are the same as the original repo from felipec.

Since you have done quite a few commits, do you plan to do a new release? (i.e. a v0.4 tag)
I would encurage you to do that, as that makes packaging easier.

**Comment by mnauw** [comment]
So far I had not added a tag as it seemed that most distributions were still using the original repo.
However, if there is some interest as in this case, then it is of course no problem to add a tag.
So I just added a v0.4 on the current master, which as I understand it is all that is needed.

Also, feel free to mention if there are other things that can make packaging easier.

**Comment by pirat89** [comment]
Thanks @mnauw! From Fedora :)

**Comment by solbu** [comment]
Thank you @mnauw. It is now in Mageia too, which will be included in the next Mageia 7 release.
