### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'changectx'

### ISSUE THREAD

**Issue by lvandenb** [mnauw/git-remote-hg#21]
was mentioned by user in https://github.com/felipec/git-remote-hg/issues/72
" just added to gitrange

if hasattr(a, 'rev'):
    a = a.rev()
    b = b.rev()
"

I just had to do this today , and everything works now.

**Comment by mnauw** [comment]
Thank you for mentioning this.  However, I suspect you were using an older version, since such a similar change/fix has already been done in commit 5e96683f67af35475175bb057271102edb4a3c9a

**Comment by native-api** [comment]
Confirming that the bug does not happen with the current `master`.

**Comment by mnauw** [comment]
Closing in view of previous comments.
