### ISSUE TITLE
adopt/merge/rewrite recent changes in felipec's version of git-remote-hg?

### ISSUE THREAD

**Issue by pabs3** [mnauw/git-remote-hg#54]
I note that in 2022, felipec ported their version of git-remote-hg to Python 3 and made a bunch of other changes.

I don't know if any of the changes are useful to this fork but it might be worth reviewing them to find out.

**Comment by mnauw** [comment]
Thanks for the heads-up.  However, Python 3 support was added here a long time ago (in commit 59b5a8c8485897940940b8472ed8f0db5a82ae6c) in a way that makes it dual-compatible (both v2 and v3).  A quick review shows the other port to v3 to be "straight" one (without retaining v2).  

Suffice it to say it is unfortunate (understatement) for such "dual action" and "divergence" to happen.  It could be (partially) addressed by performing a merge of those commits (as a sort-of "mark of review") as has been done in the past, but I am not sure if that is helpful or applicable.

As such, I do not see more/other specific action to address this (issue).  If there are particular issues, whether or not related to v3 support/port, then those can be properly addressed.
